### ISSUE TITLE
contrast.ph-auto_contrast algorithm is incorrect

### ISSUE THREAD

**Issue by wuhaijie** [danishm/mritopng#25]
Hi, when read your code in function auto_contrast and also the link you posted:
https://stackoverflow.com/questions/9744255/instagram-lux-effect/9761841#9761841
it says: a*p5+b=0 and a*p95+b=255
Therefore, 
     b=- a*p5
     a*p95+(- a*p5)=255
and:
    a = 255/(p95-p5)
In the current implementation:
   line36:  a = 255.0/(p95 + p5)
So I think it should be:
 a = 255.0/(p95 - p5)

**Comment by danishm** [comment]
@wuhaijie Thank you for reporting this. Yes it looks like you are correct!

**Comment by wuhaijie** [comment]
@danishm  great, you are still maintaining this repo!

**Comment by danishm** [comment]
@wuhaijie I'm closing this issue with the fix you recommended. As you can see the fix was pretty simple. However, it did not fail any tests or expected results that I already head. I took some time to investigate that. It turns out that if the there is a lot of black in the data, `p5` always ends up being `0` and hence `a` always ends up being `255.0/p95`, which doesn't get changes if we do a `+` or `-`. Hence, I guess I got a little lucky over there!
